spring:
  application:
    name: postgresqlWithSpring

  datasource:
#    jdbc:postgresql://185.73.126.208:5432/hrcore
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 10000
      validation-timeout: 3000
      login-timeout: 10
      idle-timeout: 600000
      max-lifetime: 180000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        check_constraint_handling_mode: IGNORE

#logging:
#  level:
#    com.zaxxer.hikari: DEBUG
#    org:
#      hibernate: TRACE
#      hibernate.SQL: DEBUG
#      springframework:
#        jdbc: TRACE
#        orm.jpa: DEBUG