spring:
  application:
    name: postgresqlWithSpring

  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 180000

  jpa:
    hibernate:
      ddl-auto: update