spring:
  application:
    name: postgresqlWithSpring
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 10000
      validation-timeout: 3000
      login-timeout: 10
      idle-timeout: 600000
      max-lifetime: 180000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hbm2ddl.auto: validate

  jackson:
    deserialization:
      fail-on-unknown-properties: true

#logging:
#  level:
#    com.zaxxer.hikari: DEBUG
#    org:
#      hibernate: TRACE
#      hibernate.SQL: DEBUG
#      springframework:
#        jdbc: TRACE
#        orm.jpa: DEBUG